name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest json-c
      run: |
        git clone https://github.com/json-c/json-c.git
        cd json-c
        sh autoget.sh
        ./configure
        make
        sudo make install
        cd ..
    - name: Install other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdwarf-dev libelf-dev libsqlite3-dev gperf nodejs npm
        npm install vsce
    - name: make
      run: make
