name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install latest json-c
      run: |
        git clone https://github.com/json-c/json-c.git
        cd json-c
        sh autogen.sh
        ./configure
        make
        sudo make install
        cd ..
    - name: install other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdwarf-dev libelf-dev libsqlite3-dev gperf nodejs npm bison flex
        sudo npm install vsce -g
    - name: make
      run: make
    - name: test
      run: make tests
