name: Build/Test

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install json-c 0.13
      run: |
        git clone https://github.com/json-c/json-c.git
        cd json-c
        git checkout tags/json-c-0.13.1-20180305
        sh autogen.sh
        ./configure
        make
        sudo make install
        cd ..
    - name: Install other dependencies
      run: |
        sudo apt-get install -y libdwarf-dev libelf-dev libsqlite3-dev gperf nodejs npm bison flex libbpfcc-dev libfl-dev
        sudo npm install vsce -g
    - name: Make everything
      run: make
    - name: Install
      run: sudo make -C record install
    - name: Run tests
      run: cd test && make run
    - name: Save Record artifact
      uses: actions/upload-artifact@v1
      with:
        name: record
        path: record/fr_record
    - name: Save Preload artifact
      uses: actions/upload-artifact@v1
      with:
        name: preload
        path: record/fr_preload.so
    - name: Save VS Code extension artifact
      uses: actions/upload-artifact@v1
      with:
        name: vscode_extension
        path: vscode_extension/flightrec-0.1.0.vsix

